name: CI

on: [push]

permissions:
  contents: read

jobs:
  sast_scan: # static application security testing
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 #this action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  #always upload the artifact even if the job fails
      # This action uploads artifacts from your workflow to GitHub, so you can access them later
      if: always()    
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1

    - name: Build Docker Image
      run: sudo docker build -f Dockerfile -t myapp:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.0.9
      with:
        dockerhub-user: ${{ secrets.REPO_USER }}
        dockerhub-password: ${{ secrets.REPO_PASSWORD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif

    - name: Debug List Files
      run: ls -la

    - name: Debug Check scout-report.sarif content
      run: |
        if [ -f scout-report.sarif ]; then
          echo "scout-report.sarif found."
          cat scout-report.sarif
        else
          echo "scout-report.sarif not found."
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif







